version: '3.7'

# services:

#   sample:
#     container_name: sample
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - '.:/app'
#       - '/app/node_modules'
#     ports:
#       - 3001:3000
#       - 443:443
#     environment:
#       - FORCE_HTTPS=true
#       - CHOKIDAR_USEPOLLING=true
      

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "3002:80"
      - "3003:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - web

  web:
    build: ./
    environment:
      - VIRTUAL_HOST=foo.test
      - VIRTUAL_PORT=8080